spring:
  datasource:
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: 20010119
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8081